--
-- PostgreSQL database dump
--



-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

-- Started on 2026-03-27 14:31:59

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE ONLY public.carrito DROP CONSTRAINT fk_carrito_user;
ALTER TABLE ONLY public.carrito DROP CONSTRAINT fk_carrito_component;
ALTER TABLE ONLY public.users DROP CONSTRAINT users_pkey;
ALTER TABLE ONLY public.users DROP CONSTRAINT users_email_key;
ALTER TABLE ONLY public.components DROP CONSTRAINT components_pkey;
ALTER TABLE ONLY public.carrito DROP CONSTRAINT carrito_pkey;
ALTER TABLE public.carrito ALTER COLUMN id DROP DEFAULT;
DROP TABLE public.users;
DROP TABLE public.components;
DROP SEQUENCE public.carrito_id_seq;
DROP TABLE public.carrito;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 224 (class 1259 OID 32785)
-- Name: carrito; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.carrito (
    id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    component_id bigint NOT NULL,
    quantity integer NOT NULL
);


ALTER TABLE public.carrito OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 32784)
-- Name: carrito_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.carrito_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.carrito_id_seq OWNER TO postgres;

--
-- TOC entry 5035 (class 0 OID 0)
-- Dependencies: 223
-- Name: carrito_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.carrito_id_seq OWNED BY public.carrito.id;


--
-- TOC entry 220 (class 1259 OID 24723)
-- Name: components; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.components (
    price numeric(10,2),
    stock integer,
    id bigint NOT NULL,
    brand character varying(255),
    category character varying(255),
    compatibility_tag character varying(255),
    performance_level character varying(255),
    product_name character varying(255) NOT NULL
);


ALTER TABLE public.components OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 24722)
-- Name: components_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.components ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.components_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 24733)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    birthdate timestamp(6) without time zone,
    id bigint NOT NULL,
    email character varying(255),
    name character varying(255),
    password character varying(255),
    rol character varying(255)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 24732)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4866 (class 2604 OID 32788)
-- Name: carrito id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carrito ALTER COLUMN id SET DEFAULT nextval('public.carrito_id_seq'::regclass);


--
-- TOC entry 5029 (class 0 OID 32785)
-- Dependencies: 224
-- Data for Name: carrito; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.carrito VALUES (186, 16, 34, 1);
INSERT INTO public.carrito VALUES (187, 16, 7, 1);
INSERT INTO public.carrito VALUES (188, 16, 21, 1);
INSERT INTO public.carrito VALUES (189, 16, 45, 1);
INSERT INTO public.carrito VALUES (190, 16, 52, 1);
INSERT INTO public.carrito VALUES (191, 16, 60, 1);
INSERT INTO public.carrito VALUES (192, 16, 66, 1);


--
-- TOC entry 5025 (class 0 OID 24723)
-- Dependencies: 220
-- Data for Name: components; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.components VALUES (55.00, 100, 1, 'AMD', 'CPU', 'AM4', 'Oficina', 'AMD Athlon 3000G');
INSERT INTO public.components VALUES (82.00, 50, 2, 'Intel', 'CPU', 'LGA1700', 'Oficina', 'Intel Pentium Gold G7400');
INSERT INTO public.components VALUES (98.00, 45, 3, 'Intel', 'CPU', 'LGA1700', 'Gama Baja', 'Intel Core i3-12100F');
INSERT INTO public.components VALUES (79.00, 30, 4, 'AMD', 'CPU', 'AM4', 'Gama Baja', 'AMD Ryzen 5 4500');
INSERT INTO public.components VALUES (95.00, 40, 5, 'AMD', 'CPU', 'AM4', 'Gama Baja', 'AMD Ryzen 5 5500');
INSERT INTO public.components VALUES (145.00, 60, 6, 'Intel', 'CPU', 'LGA1700', 'Gama Media', 'Intel Core i5-12400F');
INSERT INTO public.components VALUES (165.00, 60, 7, 'AMD', 'CPU', 'AM4', 'Gama Media', 'AMD Ryzen 5 5600X');
INSERT INTO public.components VALUES (190.00, 35, 8, 'AMD', 'CPU', 'AM4', 'Gama Media-Alta', 'AMD Ryzen 7 5700X');
INSERT INTO public.components VALUES (315.00, 25, 9, 'Intel', 'CPU', 'LGA1700', 'Gama Media-Alta', 'Intel Core i5-13600K');
INSERT INTO public.components VALUES (230.00, 30, 10, 'AMD', 'CPU', 'AM5', 'Gama Media', 'AMD Ryzen 5 7600X');
INSERT INTO public.components VALUES (320.00, 20, 11, 'AMD', 'CPU', 'AM5', 'Gama Alta', 'AMD Ryzen 7 7700X');
INSERT INTO public.components VALUES (415.00, 15, 12, 'AMD', 'CPU', 'AM5', 'Gama Alta (Gaming)', 'AMD Ryzen 7 7800X3D');
INSERT INTO public.components VALUES (435.00, 20, 13, 'Intel', 'CPU', 'LGA1700', 'Gama Alta', 'Intel Core i7-14700K');
INSERT INTO public.components VALUES (450.00, 10, 14, 'AMD', 'CPU', 'AM5', 'Entusiasta', 'AMD Ryzen 9 7900X');
INSERT INTO public.components VALUES (670.00, 12, 15, 'AMD', 'CPU', 'AM5', 'Entusiasta', 'AMD Ryzen 9 7950X3D');
INSERT INTO public.components VALUES (610.00, 10, 16, 'Intel', 'CPU', 'LGA1700', 'Entusiasta', 'Intel Core i9-14900K');
INSERT INTO public.components VALUES (740.00, 5, 17, 'Intel', 'CPU', 'LGA1700', 'Extremo', 'Intel Core i9-14900KS');
INSERT INTO public.components VALUES (49.00, 100, 18, 'OEM', 'PLACA_BASE', 'UNIVERSAL', 'Oficina', 'Placa Base OEM H510');
INSERT INTO public.components VALUES (66.00, 40, 19, 'MSI', 'PLACA_BASE', 'AM4', 'Gama Baja', 'MSI A520M-A PRO');
INSERT INTO public.components VALUES (58.00, 30, 20, 'ASUS', 'PLACA_BASE', 'AM4', 'Gama Baja', 'ASUS Prime A320M-K');
INSERT INTO public.components VALUES (82.00, 25, 21, 'Gigabyte', 'PLACA_BASE', 'LGA1700', 'Gama Baja', 'Gigabyte H610M S2H');
INSERT INTO public.components VALUES (105.00, 35, 22, 'ASUS', 'PLACA_BASE', 'AM4', 'Gama Media', 'ASUS Prime B550M-A');
INSERT INTO public.components VALUES (185.00, 20, 23, 'MSI', 'PLACA_BASE', 'LGA1700', 'Gama Media-Alta', 'MSI MAG B760 TOMAHAWK');
INSERT INTO public.components VALUES (215.00, 15, 24, 'Gigabyte', 'PLACA_BASE', 'AM5', 'Gama Media-Alta', 'Gigabyte B650 AORUS ELITE');
INSERT INTO public.components VALUES (420.00, 10, 25, 'ASUS', 'PLACA_BASE', 'AM5', 'Gama Alta', 'ASUS ROG STRIX X670E-F');
INSERT INTO public.components VALUES (630.00, 5, 26, 'MSI', 'PLACA_BASE', 'LGA1700', 'Entusiasta', 'MSI MEG Z790 ACE');
INSERT INTO public.components VALUES (560.00, 5, 27, 'ASRock', 'PLACA_BASE', 'AM5', 'Entusiasta', 'ASRock X670E Taichi');
INSERT INTO public.components VALUES (1150.00, 2, 28, 'ASUS', 'PLACA_BASE', 'LGA1700', 'Extremo', 'ROG MAXIMUS Z790 EXTREME');
INSERT INTO public.components VALUES (48.00, 50, 29, 'ASUS', 'GPU', 'UNIVERSAL', 'Oficina', 'NVIDIA GT 710 2GB');
INSERT INTO public.components VALUES (89.00, 30, 30, 'Gigabyte', 'GPU', 'UNIVERSAL', 'Oficina', 'NVIDIA GT 1030 2GB');
INSERT INTO public.components VALUES (135.00, 20, 31, 'Sapphire', 'GPU', 'UNIVERSAL', 'Gama Baja', 'AMD Radeon RX 6400');
INSERT INTO public.components VALUES (165.00, 25, 32, 'PowerColor', 'GPU', 'UNIVERSAL', 'Gama Baja', 'AMD Radeon RX 6500 XT');
INSERT INTO public.components VALUES (195.00, 35, 33, 'MSI', 'GPU', 'UNIVERSAL', 'Gama Baja', 'NVIDIA RTX 3050 6GB');
INSERT INTO public.components VALUES (310.00, 45, 34, 'Zotac', 'GPU', 'UNIVERSAL', 'Gama Media', 'NVIDIA RTX 4060 8GB');
INSERT INTO public.components VALUES (285.00, 30, 35, 'Sapphire', 'GPU', 'UNIVERSAL', 'Gama Media', 'AMD Radeon RX 7600');
INSERT INTO public.components VALUES (460.00, 20, 36, 'Gigabyte', 'GPU', 'UNIVERSAL', 'Gama Media-Alta', 'NVIDIA RTX 4060 Ti 16GB');
INSERT INTO public.components VALUES (540.00, 15, 37, 'ASUS', 'GPU', 'UNIVERSAL', 'Gama Alta', 'AMD Radeon RX 7800 XT');
INSERT INTO public.components VALUES (665.00, 18, 38, 'ASUS', 'GPU', 'UNIVERSAL', 'Gama Alta', 'NVIDIA RTX 4070 Super');
INSERT INTO public.components VALUES (1120.00, 10, 39, 'MSI', 'GPU', 'UNIVERSAL', 'Entusiasta', 'NVIDIA RTX 4080 Super');
INSERT INTO public.components VALUES (995.00, 8, 40, 'XFX', 'GPU', 'UNIVERSAL', 'Entusiasta', 'AMD Radeon RX 7900 XTX');
INSERT INTO public.components VALUES (2150.00, 3, 41, 'ROG Strix', 'GPU', 'UNIVERSAL', 'Extremo', 'NVIDIA RTX 4090 24GB OC');
INSERT INTO public.components VALUES (14.00, 100, 42, 'Generic', 'RAM', 'UNIVERSAL', 'Oficina', 'DDR4 4GB 2400MHz Basic');
INSERT INTO public.components VALUES (24.00, 80, 43, 'Kingston', 'RAM', 'UNIVERSAL', 'Gama Baja', 'Kingston Fury 8GB DDR4');
INSERT INTO public.components VALUES (49.00, 120, 44, 'Corsair', 'RAM', 'UNIVERSAL', 'Gama Media', 'Corsair Vengeance 16GB (2x8) DDR4');
INSERT INTO public.components VALUES (88.00, 60, 45, 'G.Skill', 'RAM', 'UNIVERSAL', 'Gama Alta', 'G.Skill Ripjaws 32GB (2x16) DDR4');
INSERT INTO public.components VALUES (65.00, 50, 46, 'Crucial', 'RAM', 'UNIVERSAL', 'Gama Media', 'Crucial 16GB (2x8) DDR5 4800');
INSERT INTO public.components VALUES (135.00, 45, 47, 'Corsair', 'RAM', 'UNIVERSAL', 'Gama Alta', 'Corsair Vengeance 32GB (2x16) DDR5 6000');
INSERT INTO public.components VALUES (275.00, 15, 48, 'G.Skill', 'RAM', 'UNIVERSAL', 'Entusiasta', 'G.Skill Trident Z5 64GB DDR5 6400');
INSERT INTO public.components VALUES (540.00, 5, 49, 'Corsair', 'RAM', 'UNIVERSAL', 'Extremo', 'Dominator Titanium 96GB DDR5');
INSERT INTO public.components VALUES (12.00, 150, 50, 'Generic', 'SSD', 'UNIVERSAL', 'Oficina', 'SSD 120GB SATA OEM');
INSERT INTO public.components VALUES (21.00, 100, 51, 'Kingston', 'SSD', 'UNIVERSAL', 'Gama Baja', 'Kingston A400 240GB SATA');
INSERT INTO public.components VALUES (39.00, 90, 52, 'Crucial', 'SSD', 'UNIVERSAL', 'Gama Baja', 'Crucial BX500 500GB SATA');
INSERT INTO public.components VALUES (98.00, 50, 53, 'Samsung', 'SSD', 'UNIVERSAL', 'Gama Media', 'Samsung 870 EVO 1TB SATA');
INSERT INTO public.components VALUES (75.00, 65, 54, 'Western Digital', 'SSD', 'UNIVERSAL', 'Gama Media', 'WD Blue SN580 1TB NVMe');
INSERT INTO public.components VALUES (125.00, 40, 55, 'Samsung', 'SSD', 'UNIVERSAL', 'Gama Alta', 'Samsung 990 Pro 1TB NVMe');
INSERT INTO public.components VALUES (195.00, 30, 56, 'Samsung', 'SSD', 'UNIVERSAL', 'Gama Alta', 'Samsung 990 Pro 2TB NVMe');
INSERT INTO public.components VALUES (580.00, 5, 57, 'Crucial', 'SSD', 'UNIVERSAL', 'Extremo', 'Crucial T705 4TB Gen5 NVMe');
INSERT INTO public.components VALUES (19.00, 200, 58, 'OEM', 'PSU', 'UNIVERSAL', 'Oficina', 'Fuente 500W Basic');
INSERT INTO public.components VALUES (38.00, 60, 59, 'Aerocool', 'PSU', 'UNIVERSAL', 'Gama Baja', 'Aerocool VX PLUS 600W');
INSERT INTO public.components VALUES (68.00, 50, 60, 'Corsair', 'PSU', 'UNIVERSAL', 'Gama Media', 'Corsair CV650 80+ Bronze');
INSERT INTO public.components VALUES (115.00, 30, 61, 'EVGA', 'PSU', 'UNIVERSAL', 'Gama Media-Alta', 'EVGA 750 GQ 80+ Gold');
INSERT INTO public.components VALUES (135.00, 25, 62, 'Corsair', 'PSU', 'UNIVERSAL', 'Gama Alta', 'Corsair RM850e Gold');
INSERT INTO public.components VALUES (295.00, 12, 63, 'Seasonic', 'PSU', 'UNIVERSAL', 'Entusiasta', 'Seasonic PRIME 1000W Platinum');
INSERT INTO public.components VALUES (580.00, 4, 64, 'ASUS', 'PSU', 'UNIVERSAL', 'Extremo', 'ROG Thor 1600W Titanium');
INSERT INTO public.components VALUES (24.00, 100, 65, 'OEM', 'CASE', 'UNIVERSAL', 'Oficina', 'Caja Oficina Micro-ATX');
INSERT INTO public.components VALUES (32.00, 50, 66, 'Nox', 'CASE', 'UNIVERSAL', 'Gama Baja', 'Nox Forte USB 3.0');
INSERT INTO public.components VALUES (49.00, 40, 67, 'Tempest', 'CASE', 'UNIVERSAL', 'Gama Media', 'Tempest Soul RGB White');
INSERT INTO public.components VALUES (95.00, 25, 68, 'NZXT', 'CASE', 'UNIVERSAL', 'Gama Media-Alta', 'NZXT H5 Flow Black');
INSERT INTO public.components VALUES (105.00, 30, 69, 'Corsair', 'CASE', 'UNIVERSAL', 'Gama Alta', 'Corsair 4000D Airflow');
INSERT INTO public.components VALUES (195.00, 15, 70, 'Lian Li', 'CASE', 'UNIVERSAL', 'Entusiasta', 'Lian Li O11 Dynamic EVO');
INSERT INTO public.components VALUES (560.00, 3, 71, 'Corsair', 'CASE', 'UNIVERSAL', 'Extremo', 'Corsair 1000D Super Tower');
INSERT INTO public.components VALUES (9.00, 200, 72, 'HP', 'RATON', 'UNIVERSAL', 'Oficina', 'Raton HP M100 USB');
INSERT INTO public.components VALUES (28.00, 80, 73, 'Logitech', 'RATON', 'UNIVERSAL', 'Gaming Baja', 'Logitech G203 Lightsync');
INSERT INTO public.components VALUES (56.00, 60, 74, 'Logitech', 'RATON', 'UNIVERSAL', 'Gaming Alta', 'Logitech G502 Hero');
INSERT INTO public.components VALUES (145.00, 20, 75, 'Razer', 'RATON', 'UNIVERSAL', 'Gaming Profesional', 'Razer DeathAdder V3 Pro');
INSERT INTO public.components VALUES (14.00, 150, 76, 'Logitech', 'TECLADO', 'UNIVERSAL', 'Oficina', 'Teclado Logitech K120');
INSERT INTO public.components VALUES (59.00, 40, 77, 'Corsair', 'TECLADO', 'UNIVERSAL', 'Gaming Media', 'Corsair K55 RGB PRO');
INSERT INTO public.components VALUES (240.00, 15, 78, 'Razer', 'TECLADO', 'UNIVERSAL', 'Gaming Profesional', 'Razer Huntsman V3 Pro');
INSERT INTO public.components VALUES (115.00, 50, 79, 'LG', 'MONITOR', 'UNIVERSAL', 'Oficina', 'Monitor LG 24" FHD 75Hz');
INSERT INTO public.components VALUES (285.00, 25, 80, 'MSI', 'MONITOR', 'UNIVERSAL', 'Gaming Alta', 'Monitor MSI 27" QHD 170Hz');
INSERT INTO public.components VALUES (1350.00, 5, 81, 'Samsung', 'MONITOR', 'UNIVERSAL', 'Extremo', 'Samsung Odyssey G9 49" Curvo');


--
-- TOC entry 5027 (class 0 OID 24733)
-- Dependencies: 222
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.users VALUES (NULL, 5, 'javi@gmail.com', NULL, '$2a$10$/Q1TbZBiPccQ92qCP/Wd..p2DF0.Ns9mZbBARRuG4Vl6VxDIO7axy', NULL);
INSERT INTO public.users VALUES (NULL, 6, 'alonso@gmail.com', NULL, '$2a$10$BieaB3s2tIyCVi32lgGA1ulRWcT4QuFIXCG43nJQpqaLsyoaJ5Doq', NULL);
INSERT INTO public.users VALUES (NULL, 7, 'alonso1@gmail.com', NULL, '$2a$10$1Lc4prtvRt2yETnBM8jPGOAWhUTS2Rw0azGma9qpYNicDVbFCz1Da', NULL);
INSERT INTO public.users VALUES (NULL, 8, 'pablo@gmail.com', NULL, '$2a$10$VlVlbEV7Lx8A8OC9/wit4eZZq/mO/tRhAm57ey5KVvb4vRuX4W1TC', NULL);
INSERT INTO public.users VALUES (NULL, 9, 'Laurita@gmail.com', NULL, '$2a$10$tihBOluPLZ5Uhjr6OEcwQeIhmBeR69cVi4DnnJKxz0fIUKN3rz/w2', NULL);
INSERT INTO public.users VALUES (NULL, 10, 'EnriqueColorsilla@gmail.com', NULL, '$2a$10$WdEYxzMdmF9MgBT9GJkOj.SS2EHh1lfvnYj8CYFGiIPqbdqU5XzfW', NULL);
INSERT INTO public.users VALUES (NULL, 12, 'pepe@gmail.com', NULL, '$2a$10$BcuzCVDtQvtcEJ5LfyrNEuQDS3jtvgEj6r1ikrW8/c5.J1oSQamN6', NULL);
INSERT INTO public.users VALUES (NULL, 13, 'pepe1@gmail.com', NULL, '$2a$10$gUTE5s6WGsw3f/sOZ4EEturkYcMJRd1U2vdWBrEIux/TgaMSLJGWu', NULL);
INSERT INTO public.users VALUES (NULL, 14, 'Enriquecolorsilla1@gmail.com', NULL, '$2a$10$RF2vUL0t9reIDTFW0Pt1o.HXQLG5On61DeNmu5o7SU6zfBSn4ntwu', NULL);
INSERT INTO public.users VALUES (NULL, 15, 'samu123@gmail.com', NULL, '$2a$10$tmL9kOvTPtfzTTR/..aCOOb2Vg0s0OR.tfZ85vkCQI2yHVq7t5xWO', NULL);
INSERT INTO public.users VALUES (NULL, 16, 'alonso12@gmail.com', NULL, '$2a$10$wFrPzKmWJShlQC9E3IlBWuVZJ2gt4/wcsktfkg2tjYYzyS3Ve3xSG', NULL);
INSERT INTO public.users VALUES (NULL, 17, 'alonso123@gmail.com', NULL, '$2a$10$izrJ4JlxbIIHbfKPbOC/BuW3DVtsNZb3uaQpTUWZAhYGZhUaZsu7C', NULL);


--
-- TOC entry 5036 (class 0 OID 0)
-- Dependencies: 223
-- Name: carrito_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

-- SELECT pg_catalog.setval('public.carrito_id_seq', 192, true);


--
-- TOC entry 5037 (class 0 OID 0)
-- Dependencies: 219
-- Name: components_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

-- SELECT pg_catalog.setval('public.components_id_seq', 81, true);


--
-- TOC entry 5038 (class 0 OID 0)
-- Dependencies: 221
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

-- SELECT pg_catalog.setval('public.users_id_seq', 17, true);


--
-- TOC entry 4874 (class 2606 OID 32794)
-- Name: carrito carrito_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carrito
    ADD CONSTRAINT carrito_pkey PRIMARY KEY (id);


--
-- TOC entry 4868 (class 2606 OID 24731)
-- Name: components components_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.components
    ADD CONSTRAINT components_pkey PRIMARY KEY (id);


--
-- TOC entry 4870 (class 2606 OID 24742)
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- TOC entry 4872 (class 2606 OID 24740)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4875 (class 2606 OID 32800)
-- Name: carrito fk_carrito_component; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carrito
    ADD CONSTRAINT fk_carrito_component FOREIGN KEY (component_id) REFERENCES public.components(id) ON DELETE CASCADE;


--
-- TOC entry 4876 (class 2606 OID 32795)
-- Name: carrito fk_carrito_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carrito
    ADD CONSTRAINT fk_carrito_user FOREIGN KEY (usuario_id) REFERENCES public.users(id) ON DELETE CASCADE;


-- Completed on 2026-03-27 14:31:59

--
-- PostgreSQL database dump complete
--



