# spring.application.name=sitoinformatic
# jwt.secret=444984DAS498G4DGSDGSG494984SDA8419648FAS4987416654S8A4D94

# spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?createDatabaseIfNotExist=true   222
# # spring.datasource.url=jdbc:postgresql://localhost:5432/sito_informatic
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.datasource.username=postgres
# spring.datasource.password=1407

# # Dialecto correcto
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# # 1. Fuerza la creación limpia (BORRA Y CREA)
# # spring.jpa.hibernate.ddl-auto=create
# spring.jpa.hibernate.ddl-auto=update
# # 2. Ejecución del script masivo
# spring.jpa.defer-datasource-initialization=true
# spring.sql.init.mode=always
# spring.sql.init.data-locations=classpath:import.sql

# logging.level.org.springframework.jdbc.datasource.init=DEBUG

spring.application.name=sitoinformatic
jwt.secret=444984DAS498G4DGSDGSG494984SDA8419648FAS4987416654S8A4D94

# Cambiamos PostgreSQL por H2 en memoria
spring.datasource.url=jdbc:h2:mem:sito_informatic;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Forzar la creación de tablas e inyección del script
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:import.sql

logging.level.org.springframework.jdbc.datasource.init=DEBUG